name: Build and Package CoreVar Web Tools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore and Build Projects
      run: |
        dotnet restore
        dotnet build ./WebTools.Razor/WebTools.Razor.csproj --configuration Release --no-restore
        dotnet build ./WebTools/WebTools.csproj --configuration Release --no-restore
      working-directory: ./src

    - name: Pack
      run: |
        dotnet pack ./WebTools.Razor/WebTools.Razor.csproj -c Release -o nupkgs /p:PackageVersion=0.7.0-prerelease-${{ github.run_number }}
        dotnet pack ./WebTools/WebTools.csproj -c Release -o nupkgs /p:PackageVersion=0.7.0-prerelease-${{ github.run_number }}
      working-directory: ./src

    - name: Upload NuGet Package as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NuGet-Packages
        path: ./src/nupkgs/*.nupkg


    - name: Publish NuGet Packages
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_PUBLISH_KEY }} --source https://api.nuget.org/v3/index.json
      working-directory: ./src
